INSERT INTO chapters(id, game_id, name) VALUES
(1, 1, 'Chapter 1 - The Coutesy Call'),
(2, 1, 'Chapter 2 - The Cold Boot'),
(3, 1, 'Chapter 3 - The Return'),
(4, 1, 'Chapter 4 - The Surprise'),
(5, 1, 'Chapter 5 - The Escape'),
(6, 1, 'Chapter 6 - The Fall'),
(7, 1, 'Chapter 7 - The Reunion'),
(8, 1, 'Chapter 8 - The Itch'),
(9, 1, 'Chapter 9 - The Part Where He Kills You'),
(10, 2, 'Course 0 - Introduction'),
(11, 2, 'Course 1 - Team Building'),
(12, 2, 'Course 2 - Mass And Velocity'),
(13, 2, 'Course 3 - Hard-Light Surfaces'),
(14, 2, 'Course 4 - Excursion Funnels'),
(15, 2, 'Course 5 - Mobility Gels'),
(16, 2, 'Course 6 - Art Therapy');