INSERT INTO maps(game_id, chapter_id, name, description, showcase, is_disabled) VALUES
-- Portal 2 Singleplayer
-- 1
(1,1,'Container Ride','','',true),
(1,1,'Portal Carousel','','',true),
(1,1,'Portal Gun','','',false),
(1,1,'Smooth Jazz','','',false),
(1,1,'Cube Momentum','','',false),
(1,1,'Future Starter','','',false),
(1,1,'Secret Panel','','',false),
(1,1,'Wakeup','','',true),
(1,1,'Incinerator','','',false),
-- 2
(1,2,'Laser Intro','','',false),
(1,2,'Laser Stairs','','',false),
(1,2,'Dual Lasers','','',false),
(1,2,'Laser Over Goo','','',false),
(1,2,'Catapult Intro','','',false),
(1,2,'Trust Fling','','',false),
(1,2,'Pit Flings','','',false),
(1,2,'Fizzler Intro','','',false),
-- 3
(1,3,'Ceiling Catapult','','',false),
(1,3,'Ricochet','','',false),
(1,3,'Bridge Intro','','',false),
(1,3,'Bridge The Gap','','',false),
(1,3,'Turret Intro','','',false),
(1,3,'Laser Relays','','',false),
(1,3,'Turret Blocker','','',false),
(1,3,'Laser vs Turret','','',false),
(1,3,'Pull The Rug','','',false),
-- 4
(1,4,'Column Blocker','','',false),
(1,4,'Laser Chaining','','',false),
(1,4,'Triple Laser','','',false),
(1,4,'Jail Break','','',false),
(1,4,'Escape','','',false),
-- 5
(1,5,'Turret Factory','','',false),
(1,5,'Turret Sabotage','','',false),
(1,5,'Neurotoxin Sabotage','','',false),
(1,5,'Core','','',false),
-- 6
(1,6,'Underground','','',false),
(1,6,'Cave Johnson','','',false),
(1,6,'Repulsion Intro','','',false),
(1,6,'Bomb Flings','','',false),
(1,6,'Crazy Box','','',false),
(1,6,'PotatOS','','',false),
-- 7
(1,7,'Propulsion Intro','','',false),
(1,7,'Propulsion Flings','','',false),
(1,7,'Conversion Intro','','',false),
(1,7,'Three Gels','','',false),
-- 8
(1,8,'Test','','',false),
(1,8,'Funnel Intro','','',false),
(1,8,'Ceiling Button','','',false),
(1,8,'Wall Button','','',false),
(1,8,'Polarity','','',false),
(1,8,'Funnel Catch','','',false),
(1,8,'Stop The Box','','',false),
(1,8,'Laser Catapult','','',false),
(1,8,'Laser Platform','','',false),
(1,8,'Propulsion Catch','','',false),
(1,8,'Repulsion Polarity','','',false),
-- 9
(1,9,'Finale 1','','',false),
(1,9,'Finale 2','','',false),
(1,9,'Finale 3','','',false),
(1,9,'Finale 4','','',false),
-- Portal 2 Cooperative
-- 0
(2,10,'Calibration','','',true),
(2,10,'Hub','','',true),
-- 1
(2,11,'Doors','','',false),
(2,11,'Buttons','','',false),
(2,11,'Lasers','','',false),
(2,11,'Rat Maze','','',false),
(2,11,'Laser Crusher','','',false),
(2,11,'Behind The Scenes','','',false),
-- 2
(2,12,'Flings','','',false),
(2,12,'Infinifling','','',false),
(2,12,'Team Retrieval','','',false),
(2,12,'Vertical Flings','','',false),
(2,12,'Catapults','','',false),
(2,12,'Multifling','','',false),
(2,12,'Fling Crushers','','',false),
(2,12,'Industrial Fan','','',false),
-- 3
(2,13,'Cooperative Bridges','','',false),
(2,13,'Bridge Swap','','',false),
(2,13,'Fling Block','','',false),
(2,13,'Catapult Block','','',false),
(2,13,'Bridge Fling','','',false),
(2,13,'Turret Walls','','',false),
(2,13,'Turret Assasin','','',false),
(2,13,'Bridge Testing','','',false),
-- 4
(2,14,'Cooperative Funnels','','',false),
(2,14,'Funnel Drill','','',false),
(2,14,'Funnel Catch','','',false),
(2,14,'Funnel Laser','','',false),
(2,14,'Cooperative Polarity','','',false),
(2,14,'Funnel Hop','','',false),
(2,14,'Advanced Polarity','','',false),
(2,14,'Funnel Maze','','',false),
(2,14,'Turret Warehouse','','',false),
-- 5
(2,15,'Repulsion Jumps','','',false),
(2,15,'Double Bounce','','',false),
(2,15,'Bridge Repulsion','','',false),
(2,15,'Wall Repulsion','','',false),
(2,15,'Propulsion Crushers','','',false),
(2,15,'Turret Ninja','','',false),
(2,15,'Propulsion Retrieval','','',false),
(2,15,'Vault Entrance','','',false),
-- 6
(2,16,'Seperation','','',false),
(2,16,'Triple Axis','','',false),
(2,16,'Catapult Catch','','',false),
(2,16,'Bridge Gels','','',false),
(2,16,'Maintenance','','',false),
(2,16,'Bridge Catch','','',false),
(2,16,'Double Lift','','',false),
(2,16,'Gel Maze','','',false),
(2,16,'Crazier Box','','',false);