DELETE FROM maps;
INSERT INTO maps (map_name, wr_score, is_coop, is_disabled) VALUES
-- Singleplayer
-- 1
('Container Ride',0,false,true),
('Portal Carousel',0,false,true),
('Portal Gun',0,false,false),
('Smooth Jazz',0,false,false),
('Cube Momentum',1,false,false),
('Future Starter',2,false,false),
('Secret Panel',0,false,false),
('Wakeup',0,false,true),
('Incinerator',0,false,false),
-- 2
('Laser Intro',0,false,false),
('Laser Stairs',0,false,false),
('Dual Lasers',2,false,false),
('Laser Over Goo',0,false,false),
('Catapult Intro',0,false,true),
('Trust Fling',2,false,false),
('Pit Flings',0,false,false),
('Fizzler Intro',2,false,false),
-- 3
('Ceiling Catapult',0,false,false),
('Ricochet',2,false,false),
('Bridge Intro',2,false,false),
('Bridge The Gap',0,false,false),
('Turret Intro',0,false,false),
('Laser Relays',0,false,false),
('Turret Blocker',0,false,false),
('Laser vs Turret',0,false,false),
('Pull The Rug',0,false,false),
-- 4
('Column Blocker',0,false,false),
('Laser Chaining',0,false,false),
('Triple Laser',0,false,false),
('Jail Break',2,false,false),
('Escape',0,false,false),
-- 5
('Turret Factory',5,false,false),
('Turret Sabotage',4,false,false),
('Neurotoxin Sabotage',0,false,false),
('Tube Ride',0,false,true),
('Core',2,false,false),
-- 6
('Long Fall',0,false,true),
('Underground',4,false,false),
('Cave Johnson',4,false,false),
('Repulsion Intro',0,false,false),
('Bomb Flings',3,false,false),
('Crazy Box',0,false,false),
('PotatOS',5,false,false),
-- 7
('Propulsion Intro',2,false,false),
('Propulsion Flings',0,false,false),
('Conversion Intro',9,false,false),
('Three Gels',4,false,false),
-- 8
('Test',2,false,false),
('Funnel Intro',0,false,false),
('Ceiling Button',0,false,false),
('Wall Button',0,false,false),
('Polarity',0,false,false),
('Funnel Catch',2,false,false),
('Stop The Box',0,false,false),
('Laser Catapult',0,false,false),
('Laser Platform',3,false,false),
('Propulsion Catch',0,false,false),
('Repulsion Polarity',2,false,false),
-- 9
('Finale 1',0,false,false),
('Finale 2',2,false,false),
('Finale 3',6,false,false),
('Finale 4',6,false,false),
-- Coop
-- 1
('Calibration',4,true,false),
('Hub',0,false,true),
('Doors',0,true,false),
('Buttons',2,true,false),
('Lasers',3,true,false),
('Rat Maze',2,true,false),
('Laser Crusher',0,true,false),
('Behind The Scenes',0,true,false),
-- 2
('Flings',4,true,false),
('Infinifling',0,true,false),
('Team Retrieval',0,true,false),
('Vertical Flings',2,true,false),
('Catapults',4,true,false),
('Multifling',2,true,false),
('Fling Crushers',0,true,false),
('Industrial Fan',0,true,false),
-- 3
('Cooperative Bridges',3,true,false),
('Bridge Swap',2,true,false),
('Fling Block',2,true,false),
('Catapult Block',4,true,false),
('Bridge Fling',4,true,false),
('Turret Walls',4,true,false),
('Turret Assasin',0,true,false),
('Bridge Testing',0,true,false),
-- 4
('Cooperative Funnels',0,true,false),
('Funnel Drill',0,true,false),
('Funnel Catch',0,true,false),
('Funnel Laser',0,true,false),
('Cooperative Polarity',0,true,false),
('Funnel Hop',0,true,false),
('Advanced Polarity',0,true,false),
('Funnel Maze',0,true,false),
('Turret Warehouse',0,true,false),
-- 5
('Repulsion Jumps',0,true,false),
('Double Bounce',2,true,false),
('Bridge Repulsion',2,true,false),
('Wall Repulsion',2,true,false),
('Propulsion Crushers',0,true,false),
('Turret Ninja',0,true,false),
('Propulsion Retrieval',0,true,false),
('Vault Entrance',0,true,false),
-- 6
('Seperation',0,true,false),
('Triple Axis',0,true,false),
('Catapult Catch',0,true,false),
('Bridge Gels',2,true,false),
('Maintenance',0,true,false),
('Bridge Catch',0,true,false),
('Double Lift',0,true,false),
('Gel Maze',0,true,false),
('Crazier Box',0,true,false);